# Python for mathematics, science and engineering
https://scipy.org/

## Scipy
(pronounced "Sigh Pie")

Higher level algorithms on top of `numpy`

* numerical integration
* optimization
* interpolation
* Signal Processing
* Linear Algebra
  * with sparse matrices
* statistics

In [1]:
import numpy as np
from scipy import stats
%matplotlib inline
import matplotlib.pyplot

## Statistics

The [`scipy.stats`](https://docs.scipy.org/doc/scipy/reference/stats.html) package "_contains a large number of probability distributions as well as a growing library of statistical functions_". Here we demonstrate how you can extract various statistics from a dataset.

One can import the [Iris dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set) from [`scikit-learn`](http://scikit-learn.org/stable/index.html)

* collected by Ronald Fisher (1936)
* contains 50 flower samples
* 4 parameters for each sample
  * sepal length, sepal width, petal length, petal width
* the samples are labeled according to species
  * setosa, virginica, versicolor
* the raw data is a $50\times 4$ matrix
  * the rows are labeled with $\{0,1,2\}$
<img width=200 src="petal-sepal.jpg"/>

It is often used to test machine learning algorithms, to see if they can guess the species from the size of the perianth measurements.

In [2]:
from sklearn import datasets
iris = datasets.load_iris()
print('Target names:', iris.target_names)
print('Features:', iris.feature_names)
print(iris.data)

Target names: ['setosa' 'versicolor' 'virginica']
Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9

The samples can be divided into three classes, according to the labels.

In [3]:
first = iris.data[iris.target == 0]
second = iris.data[iris.target == 1]
third = iris.data[iris.target == 2]
print(len(first), len(second), len(third))

50 50 50


### Tasks
* Calculate the class-wise mean of the data points (three 4-dimensional vectors)

Use `numpy.average`!

* Calculate the geometric mean. You won't find a function for that in `numpy`; use `scipy.stats.gmean`.

* Calculate the Pearson correlation between
  * the sepal width and length
  * the petal width and length
  * all of the above but for each of the three classes separately

Use `scipy.stats.pearsonr` for correlation!

In [4]:
cwmean_1 = np.average(first, axis=0)
cwmean_2 = np.average(second, axis=0)
cwmean_3 = np.average(third, axis=0)
print(cwmean_1, cwmean_2, cwmean_3)

gmean_1 = stats.gmean(first, axis=0)
gmean_2 = stats.gmean(second, axis=0)
gmean_3 = stats.gmean(third, axis=0)
print(gmean_1, gmean_2, gmean_3)

# features: [sep_len, sep_wid, pet_len, pet_wid]
corr_sep = stats.pearsonr(iris.data[:, 1], iris.data[:, 0])
corr_pet = stats.pearsonr(iris.data[:, 3], iris.data[:, 2])
print(corr_sep, corr_pet)

corr_sep_1 = stats.pearsonr(first[:, 1], first[:, 0])
corr_sep_2 = stats.pearsonr(second[:, 1], second[:, 0])
corr_sep_3 = stats.pearsonr(third[:, 1], third[:, 0])
print(corr_sep_1, corr_sep_2, corr_sep_3)

corr_pet_1 = stats.pearsonr(first[:, 3], first[:, 2])
corr_pet_2 = stats.pearsonr(second[:, 3], second[:, 2])
corr_pet_3 = stats.pearsonr(third[:, 3], third[:, 2])
print(corr_pet_1, corr_pet_2, corr_pet_3)

[ 5.006  3.418  1.464  0.244] [ 5.936  2.77   4.26   1.326] [ 6.588  2.974  5.552  2.026]
[ 4.99384106  3.3969062   1.45373856  0.22346247] [ 5.91397936  2.75187353  4.23308089  1.31118738] [ 6.55779452  2.95701356  5.52578887  2.00721413]
(-0.10936924995064935, 0.18276521527136649) (0.96275709705096624, 5.776660988495158e-86)
(0.74678037326392677, 4.7519865801489557e-10) (0.52591071728282457, 8.7718600119738425e-05) (0.45722781639411292, 0.00084346247237087788)
(0.30630821115803558, 0.030507161205929209) (0.78666808852281678, 1.2719157063236543e-11) (0.3221082159003183, 0.022535767279873952)


## Linear algebra

The [`scipy.linalg`](https://docs.scipy.org/doc/scipy/reference/linalg.html) module contains
- linear (equation system) solvers
- advanced matrix functions (pseudo inverse, etc.)
- matrix decomposition functions (eigen-, singular value-, etc.)
- special matrix generators
- matrix equations solvers
- etc.

A few examples follow below.

### Linear equation systems

Solves $A\cdot x = b$, where $A\in\mathbb{R}^{n\times n}, b\in \mathbb{R}^n$ for $x\in\mathbb{R}^n$.

In [5]:
from scipy import linalg


A = 0.5*(np.diag(np.ones(7), k=1) - np.diag(np.ones(7), k=-1))
b = np.ones(len(A))

print('[A|b]:\n{}'.format(np.concatenate((A, b.reshape(-1,1)), axis=1)))

x = linalg.solve(A, b)
print('x:', x)

# Let's test if the solution is correct
assert np.allclose(A.dot(x), b)

[A|b]:
[[ 0.   0.5  0.   0.   0.   0.   0.   0.   1. ]
 [-0.5  0.   0.5  0.   0.   0.   0.   0.   1. ]
 [ 0.  -0.5  0.   0.5  0.   0.   0.   0.   1. ]
 [ 0.   0.  -0.5  0.   0.5  0.   0.   0.   1. ]
 [ 0.   0.   0.  -0.5  0.   0.5  0.   0.   1. ]
 [ 0.   0.   0.   0.  -0.5  0.   0.5  0.   1. ]
 [ 0.   0.   0.   0.   0.  -0.5  0.   0.5  1. ]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0.   1. ]]
x: [-8.  2. -6.  4. -4.  6. -2.  8.]


### Least square problem

Finds optimal solution, for non-invertible coefficient matrix. Used when the equation system is _overdetermined_: there are more equations than variables:
$A\in\mathbb{R}^{n\times k}, b\in \mathbb{R}^n$ and $x\in\mathbb{R}^k, \quad n > k$.

In [6]:
A2 = (np.diag(np.ones(9), k=1) - np.diag(np.ones(10), k=0))[:-1, :].T
print('A:\n{}'.format(A2))
b2 = np.linspace(-1, 1, num=len(A2))
x2 = linalg.lstsq(A2, b2)[0]
print('b:', b2)
print('x:', x2)
# matplotlib.pyplot.plot(range(1, len(b)+1), b)
# matplotlib.pyplot.plot(range(0, len(x)), x)

# In this case, the solution is exact.
assert np.allclose(A2.dot(x2), b2)

A:
[[-1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.]]
b: [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
x: [ 1.          1.77777778  2.33333333  2.66666667  2.77777778  2.66666667
  2.33333333  1.77777778  1.        ]


## Sparse matrices

Many matrices in practice only have nonzero values in some of their cells; i.e. they are **sparse**. Storing large sparse matrices takes up a lot of memory space unneccesarily. The [`scipy.sparse`](https://docs.scipy.org/doc/scipy/reference/sparse.html) module implements memory-efficient sparse matrix classes.

However, memory-efficiency comes at a price. There are several types of sparse matrices, all with specific advantages and disadvantages. A few examples:

* Optimized for storage:
  * [`coo_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html): coordinate-data tuples
* Aimed for incrementally creating sparse matrices:
  * [`lil_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.lil_matrix.html): based on a linked list
  * [`dok_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.dok_matrix.html): based on a `dict` of `dict`s
* Optimized for arithmetic operations
  * [`csr_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html): fast row operations
  * [`csc_matrix`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csc_matrix.html): fast column operations
  
For further gotchas, see the package and matrix descriptions.

### Example

A `csc_matrix` (or `csr_matrix`) is created from three lists: values, row indices and column indices.
* below:
  * matrix values: `[1, 2, 3, 4]`
  * row indices: `[0, 1, 1, 2]`
  * col indices: `[1, 0, 2, 1]`
* meaning: 
  * $1$ is at position $(0,1)$
  * $2$ is at position $(1,0)$
  * $3$ is at position $(1,2)$
  * $4$ is at position $(2,1)$
  
We cannot print the whole sparse matrix; use
* `.todense()` to convert it into a dense matrix
* `.toarray()` to convert it into an array

first; although not recommended if the matrix is huge (why?)

In [7]:
from scipy import sparse
#from scipy import sparse.linalg
csc = sparse.csc_matrix(([1, 2, 3, 4], ([0, 1, 1, 2], [1, 0, 2, 1])), shape=(3,3), dtype=float)
print("csc:\n{}".format(csc))
print("csc.toarray():\n{}".format(csc.toarray()))
csc

csc:
  (1, 0)	2.0
  (0, 1)	1.0
  (2, 1)	4.0
  (1, 2)	3.0
csc.toarray():
[[ 0.  1.  0.]
 [ 2.  0.  3.]
 [ 0.  4.  0.]]


<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Column format>

### Sparse linear algebra

The `scipy.linalg` package has a sparse equivalent: [`scipy.sprase.linalg`](https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html). Use the latter for sparse matrices.

### Task
* Solve the linear equation system you did above with numpy.
  * call the variables `As`, `bs`, `xs` to avoid accidentally overriding the originals
  * use `scipy.sparse.diags` instead of `numpy.diag`
  * note that the signatures of the sparse functions might be different!

In [8]:
# Create As and bs
As = 0.5*(sparse.diags(np.ones(7), offsets=1) - sparse.diags(np.ones(7), offsets=-1))
bs = np.ones(8)

print('As:\n{}'.format(As.toarray()))
print('bs:', bs)

xs = sparse.linalg.spsolve(As, bs)
# Solve the equation system!
print('xs:', xs)

As:
[[ 0.   0.5  0.   0.   0.   0.   0.   0. ]
 [-0.5  0.   0.5  0.   0.   0.   0.   0. ]
 [ 0.  -0.5  0.   0.5  0.   0.   0.   0. ]
 [ 0.   0.  -0.5  0.   0.5  0.   0.   0. ]
 [ 0.   0.   0.  -0.5  0.   0.5  0.   0. ]
 [ 0.   0.   0.   0.  -0.5  0.   0.5  0. ]
 [ 0.   0.   0.   0.   0.  -0.5  0.   0.5]
 [ 0.   0.   0.   0.   0.   0.  -0.5  0. ]]
bs: [ 1.  1.  1.  1.  1.  1.  1.  1.]
xs: [-8.  2. -6.  4. -4.  6. -2.  8.]


### Decomposition example

Below we run sparse [singular value decomposition](https://en.wikipedia.org/wiki/Singular-value_decomposition) on `As`:
* first, we obtain the component matrices $U, d, V^*$ (note that these won't be sparse)
* then, we reconstruct the original matrix from them

In [10]:
def reconstruct_svd(M, k=None):
    if k is None:
        U, d, Vh = sparse.linalg.svds(M)
    else:
        U, d, Vh = sparse.linalg.svds(M, k)
    M_rec = U.dot(np.diag(d).dot(Vh))
    # Set small elements to zero
    M_rec[np.abs(M_rec) < 1e-15] = 0
    return M_rec

print("Full sparse SVD:\n{}\n".format(reconstruct_svd(A)))
print("Sparse SVD, first 2 singular values:\n{}".format(reconstruct_svd(A, 2)))

Full sparse SVD:
[[ 0.          0.47400494  0.         -0.04885474  0.         -0.06582181
   0.         -0.0748498 ]
 [-0.47400494  0.          0.52285967  0.          0.01696707  0.
   0.00902799  0.        ]
 [ 0.         -0.52285967  0.          0.45703787  0.         -0.05788273
   0.         -0.06582181]
 [ 0.04885474  0.         -0.45703787  0.          0.53188766  0.
   0.01696707  0.        ]
 [ 0.         -0.01696707  0.         -0.53188766  0.          0.45703787
   0.         -0.04885474]
 [ 0.06582181  0.          0.05788273  0.         -0.45703787  0.
   0.52285967  0.        ]
 [ 0.         -0.00902799  0.         -0.01696707  0.         -0.52285967
   0.          0.47400494]
 [ 0.0748498   0.          0.06582181  0.          0.04885474  0.
  -0.47400494  0.        ]]

Sparse SVD, first 2 singular values:
[[ 0.          0.09181687  0.         -0.1406716   0.          0.12370453
   0.         -0.04885474]
 [-0.09181687  0.          0.23248847  0.         -0.26437614  0.
 

## Document-term matrix decomposition

The [following file](http://sandbox.hlt.bme.hu/~gaebor/ea_anyag/python_nlp/movies.txt) contains (preprocessed) movie descriptions, from [CMU Movie Corpus](http://www.cs.cmu.edu/~ark/personas/).
* One movie per line
* `"title\tdescription\n"` format
* description is space separated list of words, tokenized
* Some of its UTF8  characters are broken, so we have to read it binary (byte array)

Download the file and put it in the same folder, as your notebook!

### Task 1.
* Make a vocabulary of titles (`dict` keyed by titles)
  * Each movie title should get a unique ID, from 0 to the number of movies (~39k)
  * call this `movie_to_id`
* Make a vocabulary of words (`dict` keyed by words)
  * Each word, which occurs in any of the  descriptions, should get a unique ID, from 0 to the number of unique words (~182k)
* Also make reverse vocabularies (movie id to movie title, word id to the word itself)
  * for movies, call it `id_to_movie`

In [11]:
movie_descriptions = {}
with open("movies.txt", "rb") as f:
    for i, line in enumerate(f):
        title, description = line.strip().split(b'\t')
        movie_descriptions[title] = description.split()

FileNotFoundError: [Errno 2] No such file or directory: 'movies.txt'

In [ ]:
print(len(movie_descriptions))
print(b" ".join(movie_descriptions[b"The Matrix"]))

### Task 2.
Make a sparse matrix defined in the following way:
* $a_{i,j} = $ number of times the word with ID $j$ was mentioned in the movie with ID $i$
* the rows of the matrix are movies
* columns are words
* use `float32` representation (`dtype`)

### Task 3.
* Perform a sparse SVD with k=40 and store the left singular vectors as rows (`U`) and the right singular vectors as columns (`Vh`).
* normalize the vectors (rows of `U` and columns of `Vh`) to unit length.
* $U\in\mathbb{R}^{\text{~39k}\times 40}$
* $Vh\in\mathbb{R}^{40\times \text{~182k}}$

### Task 4.
Write a function, which searches the closest vectors to a given vector.
* Use the global variable `U`
* the input is a vector $v$ and a number $k\in\mathbb{N}$.
* return the row indices of the $k$ closest vector to $v$ in $U$!

Try to use vectorization and [`numpy.argpartition`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.argpartition.html).

In [ ]:
def closests(v, k=1):
    return list(range(k))

In [ ]:
closests(np.ones(len(Vh)), 3)

Now you can search similar movies!

In [ ]:
print([id_to_movie[i] for i in closests(U[movie_to_id[b"Monsters, Inc."]], 5)])
print([id_to_movie[i] for i in closests(U[movie_to_id[b"Popeye"]], 5)])

Or even mixture of movies by adding _"movie vectors"_!

In [ ]:
[id_to_movie[i] for i in closests(U[movie_to_id[b"Popeye"]] + U[movie_to_id[b"Monsters, Inc."]], 10)]